### ISSUE TITLE
npm peer dependency warning

### ISSUE THREAD

**Issue by charlierudolph** [webpack/coffee-loader#11]
```
npm WARN peerDependencies The peer dependency coffee-script@1.x included from coffee-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by sokra** [comment]
It's a warning for your project. Add coffee-script as dependency.

**Comment by charlierudolph** [comment]
coffee-script is already a dependency in my project. It's a warning for coffee-loader that peer dependencies will not be automatically installed in the future. coffee-loader needs to move coffee-script from a peer dependency to a normal dependency.
