### ISSUE TITLE
webpack entry file cannot be a coffee script file

### ISSUE THREAD

**Issue by bsergean** [webpack/coffee-loader#13]
If there is a work-around I would use it, but I can't figure it out. I'm using browserify right now and I was looking into webpack. Here is what I have in my makefile so far (using browserify).

    coffee -w -c sm.coffee engine.coffee &
    watchify -t glslify sm.js engine.js -o bundle.js -v

Here are the files in my project: I have only 2 sources coffee files, and 2 glsl shaders.

    src$ ls
    bundle.js  engine.coffee  index.html  js  makefile  
    node_modules  sm.coffee  sm.js  vert.glsl frag.glsl sm.py webpack.config.js

Here is what my webpack.config.js file looks like: I would like to specify my entry point to be my main coffee script file.

    module.exports = {
        entry: 'engine.coffee',
        output: {
            filename: "bundle.js"
        },
        loaders: [
            { test: /\.coffee$/, loader: "coffee-loader" }
        ]
    }

It looks like I can use loaders to embed my glsl files, and to compile my cofeescript. If I'm missing something I'd appreciate it to be pointed out.

Thanks !

**Comment by mainiak** [comment]
I have similar issue. I've created demo to reproduce the issue https://gist.github.com/mainiak/1ae02e2694054f5fa6be#file-readme-md

**Comment by sokra** [comment]
`entry: './engine.coffee',`

**Comment by mainiak** [comment]
Tobias (@sokra) - As you can see in my gist, my entry point is javascript file - not coffee script file - and it doesn't work anyway.

**Comment by mainiak** [comment]
Tobias (@sokra) - if I change my gist to have JavaScript file as entry point - and require coffee script file in it - it will just throw different kind of error.

**Comment by dubharmonic** [comment]
:+1:

**Comment by joshuarh** [comment]
I'm in the same boat here. I'd like to see this implemented, as my codebase is geared around using that `index.coffee` file and without being able to specify it as an entry point it's much more difficult to take advantage of this module.

**Comment by aristidesfl** [comment]
This is working for me

**Comment by bsergean** [comment]
Looks like this is working now, I'm not very interested in this myself so if it turns out it doesn't really work, someone can file another issue.
